### PR TITLE
Update label description for `sanctioned`

### PR DESCRIPTION
**Pull request by zhanwu**
Update the label description for `sanctioned`, and re-generate the taxonomy.md file via

```
make doc-gen
```

### CODE REVIEW

**Review by beingzy — APPROVED** [review]
LGTM.

We will update this doc: https://docs.microscopeprotocol.xyz/onboarding/data/categories to reflect the changes introduce by this PR.

**Review by daerae — APPROVED** [review]

**Review by daerae — APPROVED** [review]

**Review by beingzy — APPROVED** [review]
LGTM

**Review by beingzy — APPROVED** [review]
LGTM

**Review by leozc — APPROVED** [review]

**Review by beingzy — APPROVED** [review]
LGTM

**Pull request merged**
